apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Piso Homepage
    background:
      image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
      blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
      saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
      brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
      opacity: 50 # 0-100
    layout:
      Admin:
        style: row
        columns: 4
#settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com
  services.yaml: |
      - Admin:
        - Proxmox:
            href: https://192.168.1.10:8006
            description: --
            icon: https://img.icons8.com/fluent/512/proxmox.png
            siteMonitor: https://192.168.1.10:8006
            statusStyle: "dot"

        - Kubernetes:
            href: https://192.168.1.200:32443
            description: --
            icon: https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Kubernetes_logo_without_workmark.svg/1200px-Kubernetes_logo_without_workmark.svg.png
            siteMonitor: https://192.168.1.200:32443
            statusStyle: "dot"
             #widget:
              #type: kubernetes
              #url: https://192.168.1.200:32443

        - OPNsense:
            href: https://192.168.1.11
            description: --
            icon: https://store-images.s-microsoft.com/image/apps.50971.0316e8e5-0d24-4ba0-b383-3c64f5271f6d.c2776803-acef-4e82-b6a5-24720f5f115b.76b43274-7d15-4c55-a69e-f9c6f5dd25a0
            siteMonitor: https://192.168.1.11
            statusStyle: "dot"

        - Vaultwarden:
            href: https://vaultwarden.local
            description: --
            icon: https://global.discourse-cdn.com/free1/uploads/vaultwarden/original/1X/26a1c808c7d5849039d47820eef7889b3415e5ec.png
            siteMonitor: https://vaultwarden.local
            statusStyle: "dot"
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
