apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
spec:
  ports:
    - port: 3000
      targetPort: http
  selector:
    app.kubernetes.io/name: homepage
