apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
  annotations:
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: http
      nodePort: 32000
  selector:
    app.kubernetes.io/name: homepage
